using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TechClient
{
    class Config
    {
        public int Id { get; set; }
        public int Idempresa { get; set; }
        public int Hos_apto { get; set; }
        public int Hos_barco { get; set; }
        public int Hos_piloto { get; set; }
        public int Hos_motor { get; set; }
        public int Hos_equipamento { get; set; }
        public int Hos_cozinha { get; set; }
        public DateTime Hos_viradiaria { get; set; }
        public DateTime Hos_limite { get; set; }
        public int Hos_diariaautomatica { get; set; }
        public int Hotel { get; set; }
        public int Cte { get; set; }
        public int Nfe { get; set; }
        public float Cte_alertakmoleo { get; set; }
        public float Cte_alertahorasoleo { get; set; }
        public int Cte_venceoleoveiculo { get; set; }
        public int Cte_venceoleoequip { get; set; }
        public int Cte_geraagenda { get; set; }
        public int Config_abreagenda { get; set; }
        public int Config_abremenu { get; set; }
        public int Nfe_atualizapreco { get; set; }
        public int Nfe_multiplosvendedores { get; set; }
        public int Nfe_obrigavendedor { get; set; }
        public string Nfe_modelopadrao { get; set; }
        public int Nfe_02ecf { get; set; }
        public int Nfe_entrega { get; set; }
        public string Msg_notafiscal { get; set; }
        public string Msg_relatorios { get; set; }
        public int Nfe_descontototal { get; set; }
        public string Nfe_idtoken { get; set; }
        public string Nfe_numtoken { get; set; }
        public int Ecf_barras { get; set; }
        public int Ecf_viasrel { get; set; }
        public int Ecf_obrigapaf { get; set; }
        public int Ecf_emitedav { get; set; }
        public int Ecf_emitecomb { get; set; }
        public int Ecf_emiteprod { get; set; }
        public int Ecf_obrigacaixa { get; set; }
        public string Cad_unsaida { get; set; }
        public string Cad_unentrada { get; set; }
        public int Ecf_viascc { get; set; }
        public int Cad_margem1 { get; set; }
        public int Nfe_imprimedpl { get; set; }
        public int Nfe_estoquenegativo { get; set; }
        public int Nfe_geraaut { get; set; }
        public int G_userlogado { get; set; }
        public int G_imprimecaixa { get; set; }
        public int Nfe_concdescriprod { get; set; }
        public int Nfe_obspersonaleditavel { get; set; }
        public int Nfe_obrigaoperacao { get; set; }
        public int Cad_tributacaopadrao { get; set; }
        public int Cad_cadastroautomatico { get; set; }
        public int Nfe_perguntatrib { get; set; }
        public int Nfe_pegamodefrete { get; set; }
        public int G_emitefiscal { get; set; }
        public int Paf_prioridadedav { get; set; }
        public int Paf_emiteos { get; set; }
        public int Paf_emitepedido { get; set; }
        public string G_modeloservico { get; set; }
        public int G_agrupaservico { get; set; }
        public int Ponto_tempo { get; set; }
        public int Cad_abrecadastro { get; set; }
        public int Nfe_mudadataemissao { get; set; }
        public int G_tipobuscaprod { get; set; }
        public int G_usagrade { get; set; }
        public int G_exibemedidas { get; set; }
        public int G_exibesimilares { get; set; }
        public int G_exibetransp { get; set; }
        public int Paf_stand { get; set; }
        public int G_alteranfoutrocaixa { get; set; }
        public int G_pesoautomatico { get; set; }
        public int Concatenacodigo { get; set; }
        public int Imprime_direto { get; set; }
        public int Imprime_direto_enter { get; set; }
        public int Abre_tela_preco { get; set; }
        public int Fonte_cupom { get; set; }
        public int Exibenavegador { get; set; }
        public int G_usalote { get; set; }
        public int G_usapacote { get; set; }
        public int Paf_nfdireto { get; set; }
        public int G_obrigaoperacaog { get; set; }
        public int G_automatizaopgerencial { get; set; }
        public int G_exibeacumuladores { get; set; }
        public int Cad_usaprecoprodpacote { get; set; }
        public string Estoque { get; set; }
        public int Estoque_dav { get; set; }
        public int Estoque_pre { get; set; }
        public int Estoque_ped { get; set; }
        public int Exibeestoque { get; set; }
        public int Nfe_descontopercentual { get; set; }
        public int G_obrigamecanico { get; set; }
        public int G_obrigaentregador { get; set; }
        public int G_obrigamecanicopeca { get; set; }
        public int G_preenchevendedor { get; set; }
        public string Nfe_modelopadraog { get; set; }
        public int Nfe_enviaemail { get; set; }
        public int G_exibemensagemresumocliente { get; set; }
        public int Nfe_diasgerenciador { get; set; }
        public int Nfe_visualizadanfe { get; set; }
        public int Ecf_geraarquivonaz { get; set; }
        public int Ecf_importadadosz { get; set; }
        public int Nfe_valorliquidodanfe { get; set; }
        public int Fin_diasbloqueio { get; set; }
        public int Fin_padraobloqueiodebito { get; set; }
        public int Fin_padramsgdebito { get; set; }
        public int Fin_padrabloqueialimite { get; set; }
        public int Fin_padraomsglimite { get; set; }
        public int Fin_padradebitosenha { get; set; }
        public int Fin_padraolimitesenha { get; set; }
        public int G_permitemudarvalor { get; set; }
        public int G_lancarepetido { get; set; }
        public int G_imprimepadrao { get; set; }
        public string G_codigobalanca { get; set; }
        public int G_balancapeso { get; set; }
        public int Fin_comissaovenda { get; set; }
        public int Fin_jurossimples { get; set; }
        public float Prod_descontomaximo { get; set; }
        public int Nfe_mostrarestoquevenda { get; set; }
        public int G_dataservidor { get; set; }
        public string Email_smtp { get; set; }
        public string Email_email { get; set; }
        public int Email_porta { get; set; }
        public string Email_usuario { get; set; }
        public string Email_senha { get; set; }
        public int Email_gerenciador { get; set; }
        public int Email_timeout { get; set; }
        public int Email_quantidadelote { get; set; }
        public int Nfe_abreajustepreco { get; set; }
        public int Nfe_ajustacusto { get; set; }
        public int Nfe_atualizaprecoautomatico { get; set; }
        public int Nfe_tipofretecom { get; set; }
        public int Nfe_tipofretesem { get; set; }
        public string Dav_orcamento { get; set; }
        public string Dav_pedido { get; set; }
        public string Dav_compra { get; set; }
        public string Nfe_controle { get; set; }
        public string Dav_ordemservico { get; set; }
        public int Dav_serviconoorcamento { get; set; }
        public int Prod_mostramarca { get; set; }
        public int Prod_mostragrupo { get; set; }
        public int Prod_mostrasubgrupo { get; set; }
        public int Prod_mostrabarras { get; set; }
        public int Prod_mostragerencial { get; set; }
        public int Os_mecanica { get; set; }
        public string Os_label1 { get; set; }
        public string Os_label2 { get; set; }
        public string Os_label3 { get; set; }
        public string Os_label4 { get; set; }
        public string Os_labeldata1 { get; set; }
        public string Os_labeldata2 { get; set; }
        public int Os_informatecnico { get; set; }
        public int Os_informaentregador { get; set; }
        public int Os_informasolicitante { get; set; }
        public int Pdv_mostracliente { get; set; }
        public int Pdv_usacomanda { get; set; }
        public int Nfce_contingenciaautomatica { get; set; }
        public int Cte_cfop { get; set; }
        public int Cte_tiposervico { get; set; }
        public int Cte_finalidade { get; set; }
        public int Cte_formapgto { get; set; }
        public int Cte_cst { get; set; }
        public int G_usacentrodecusto { get; set; }
        public int Nfce_imprimedireto { get; set; }
        public int Nfe_imprimedireto { get; set; }
        public int Nfce_numcopias { get; set; }
        public int Nfe_numcopias { get; set; }
        public int Nfce_escolheimpressora { get; set; }
        public int Nfe_escolheimpressora { get; set; }
        public string Nfce_nomeimpressora { get; set; }
        public string Nfe_nomeimpressora { get; set; }
        public int G_vendasocomcaixa { get; set; }
        public int Prod_mostralocal { get; set; }
        public int Prod_mostracodbalanca { get; set; }
        public int Fin_datadavduplicata { get; set; }
        public int Pdv_vendedornacomanda { get; set; }
        public int Pdv_comandacomcliente { get; set; }
        public int Pdv_mostraitens { get; set; }
        public string Fin_impressorarecibo { get; set; }
        public string Fin_impressoradpl { get; set; }
        public int Fin_imprimedpldireto { get; set; }
        public int Fin_imprimerecibodireto { get; set; }
        public int Fin_recibocopias { get; set; }
        public int Fin_dplcopias { get; set; }
        public int Pdv_mostraestoque { get; set; }
        public int Prod_tipoproduto { get; set; }
        public int Cli_precadastro { get; set; }
        public int Fin_cartaogeraduplicata { get; set; }
        public int Email_usatsl { get; set; }
        public int Email_usassl { get; set; }
        public int Nfce_geraautomatico { get; set; }
        public int Prod_delaybusca { get; set; }
        public int Prod_mostrancm { get; set; }
        public int Prod_mostrafator { get; set; }
        public int Prod_mostracest { get; set; }
        public int Prod_mostraaplicacao { get; set; }
        public int Prod_mostraalongada { get; set; }
        public int Cli_delaybusca { get; set; }
        public int Cli_mostraapelido { get; set; }
        public int Cli_mostraendereco { get; set; }
        public int Cli_mostranumero { get; set; }
        public int Cli_mostrabairro { get; set; }
        public int Cli_mostrafone01 { get; set; }
        public int Cli_mostracidade { get; set; }
        public int Cli_mostrauf { get; set; }
        public int Cli_mostracx { get; set; }
        public int Cli_mostracomple { get; set; }
        public int Cli_mostracep { get; set; }
        public int Cli_mostrafone02 { get; set; }
        public int Cli_mostrafone03 { get; set; }
        public int Cli_mostrafone04 { get; set; }
        public int Cli_mostracelular { get; set; }
        public int Cli_mostracontato { get; set; }
        public int G_delaybuscas { get; set; }
        public int Nfe_obrigabaixaroperacao { get; set; }
        public int Fin_aberturacxdireto { get; set; }
        public int Fin_aberturacxpedeimpre { get; set; }
        public int Fin_sangriadireto { get; set; }
        public int Fin_sangriaimpre { get; set; }
        public int Pdv_ocultaf11 { get; set; }
        public int Fin_imprimecarnedireto { get; set; }
        public string Fin_impressoracarne { get; set; }
        public int Fin_carnecopias { get; set; }
        public int Fin_imprimecarteiradireto { get; set; }
        public string Fin_impressoracarteira { get; set; }
        public int Fin_carteiracopias { get; set; }
        public int Fin_imprimeboletodireto { get; set; }
        public string Fin_impressoraboleto { get; set; }
        public int Fin_boletocopias { get; set; }
        public int Fin_senhaparcelaminina { get; set; }
        public int Fin_senhaparcelamaxima { get; set; }
        public int Dev_obrigaimportarde { get; set; }
        public int Dev_obrigaimportards { get; set; }
        public int Dev_denoperiodo { get; set; }
        public int Dev_dsnoperiodo { get; set; }
        public int Pdv_pesquisalike { get; set; }
        public int Cloud_sincroniza { get; set; }
        public int Prod_casasestoque { get; set; }
        public int Prod_casaspreco { get; set; }
        public string Cad_untributada { get; set; }
        public int Pdv_permitedesconto { get; set; }
        public int Dav_vencimento { get; set; }
        public int G_liberadavcomsenha { get; set; }
        public int G_liberanfcomsenha { get; set; }
        public int Dav_lancaoperacao { get; set; }
        public int Dav_lancaparcelas { get; set; }
        public int Pdv_gravalogitenscomanda { get; set; }
        public int Nf_gravalogitensnf { get; set; }
        public int Pdv_motivologitens { get; set; }
        public int Nf_motivologitens { get; set; }
        public int Nf_controlaentrega { get; set; }
        public int Nf_entregasetiverfrete { get; set; }
        public int Pdv_obrigaitemcomanda { get; set; }
        public int Pdv_btndav { get; set; }
        public int Pdv_btncadastros { get; set; }
        public int Pdv_btncupom { get; set; }
        public int Pdv_btnfinanceiro { get; set; }
        public int Pdv_btnprodutos { get; set; }
        public int Pdv_btnmenufiscal { get; set; }
        public int Pdv_btnfaturamento { get; set; }
        public string Nf_descricaomultiplas { get; set; }
        public int Nf_permitedescontototal { get; set; }
        public int Dav_permitedescontototal { get; set; }
        public string Cte_produtopredominante { get; set; }
        public int Pcg_nfentrada { get; set; }
        public int Pcg_nfsaida { get; set; }
        public int Pcg_caddplreceber { get; set; }
        public int Pcg_caddplpagar { get; set; }
        public int Pcg_movcaixa { get; set; }
        public int Pcg_movbanco { get; set; }
        public int Pcg_sangria { get; set; }
        public int Pcg_suprimento { get; set; }
        public int Pcg_usoconsumo { get; set; }
        public int Pcg_ajusteestoque { get; set; }
        public int Pcg_baixadplreceber { get; set; }
        public int Pcg_baixadplpagar { get; set; }
        public int Pcg_cte { get; set; }
        public int Pcg_mostracabecalho { get; set; }
        public int Fin_permitebaixazerada { get; set; }
        public int Nfe_mudaie { get; set; }
        public int Nfe_tsl10 { get; set; }
        public int Nfe_tsl11 { get; set; }
        public int Nfe_tsl12 { get; set; }
        public int Nfe_revogadoservidor { get; set; }
        public int Nfe_revogadofornecedor { get; set; }
        public float Fin_limitesangria { get; set; }
        public float Fin_limitesuprimento { get; set; }
        public float G_taxapercentual { get; set; }
        public float G_taxavalor { get; set; }
        public int G_utilizataxa { get; set; }
        public int G_obrigataxa { get; set; }
        public int Idconfigweb { get; set; }
        public int Sincronizado { get; set; }
        public int Nf_documentozerado { get; set; }
        public int Prod_pesquisaexata { get; set; }
        public int Pdv_pesquisaexata { get; set; }
        public int Estoque_os { get; set; }
        public int Nf_obrigalote { get; set; }
        public int Imprimeficha { get; set; }
        public int Pesquisa_quantidade { get; set; }
        public int Nf_romaneiodireto { get; set; }
        public int Nf_contratodireto { get; set; }
    }
}
