using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TechClient
{
    class Nf
    {
        public int Codigo { get; set; }
        public int Documento { get; set; }
        public int Idpessoas { get; set; }
        public DateTime Dataentrada { get; set; }
        public DateTime Dataemissao { get; set; }
        public DateTime Hora { get; set; }
        public string Tipo { get; set; }
        public int Emissor { get; set; }
        public string Chavenfe { get; set; }
        public string Modelo { get; set; }
        public int Operacao { get; set; }
        public float Valorconsumo { get; set; }
        public float Valorenergia { get; set; }
        public float Valorservico { get; set; }
        public float Valorproduto { get; set; }
        public float Valortotal { get; set; }
        public float Baseicms { get; set; }
        public float Baseicmsst { get; set; }
        public float Basepis { get; set; }
        public float Basecofins { get; set; }
        public float Baseipi { get; set; }
        public float Valoricms { get; set; }
        public float Valoricmsst { get; set; }
        public float Valorpis { get; set; }
        public float Valorcofins { get; set; }
        public float Valoripi { get; set; }
        public float Valorfrete_somado { get; set; }
        public float Valorfrete { get; set; }
        public float Valoroutros_somado { get; set; }
        public float Valoroutros { get; set; }
        public float Valordesconto { get; set; }
        public float Valoracrescimo { get; set; }
        public int Serie { get; set; }
        public int Ambiente { get; set; }
        public int Emissao { get; set; }
        public string Status { get; set; }
        public string Protocolo { get; set; }
        public string Recibo { get; set; }
        public string Horarecibo { get; set; }
        public string Observacao { get; set; }
        public string Observacaofisco { get; set; }
        public int Tipofrete { get; set; }
        public int Idtransportador { get; set; }
        public string Placa { get; set; }
        public string Ufveiculo { get; set; }
        public string Rntc { get; set; }
        public float Quantidadevolume { get; set; }
        public string Especievolume { get; set; }
        public string Marcavolume { get; set; }
        public string Numerovolume { get; set; }
        public float Pesolvolume { get; set; }
        public float Pesobvolume { get; set; }
        public DateTime Data_atualizacao { get; set; }
        public string Ufdesembarque { get; set; }
        public string Localdesembarque { get; set; }
        public int Funcionario { get; set; }
        public int Idapto { get; set; }
        public int Empresa { get; set; }
        public int Idviagem { get; set; }
        public int Idcaixa { get; set; }
        public int Idvendedor { get; set; }
        public string Nomepessoa { get; set; }
        public string Localentrega { get; set; }
        public float Comissao { get; set; }
        public string Requisitante { get; set; }
        public int Idplanovenda { get; set; }
        public int Idorigem { get; set; }
        public int Entrega { get; set; }
        public int Retirada { get; set; }
        public int Nfpropria { get; set; }
        public DateTime Horasaida { get; set; }
        public int Idecf { get; set; }
        public string Cnpjdigitado { get; set; }
        public float Percentualimp { get; set; }
        public string Comb_placa { get; set; }
        public int Comb_kmplaca { get; set; }
        public float Impostos_nac { get; set; }
        public float Impostos_imp { get; set; }
        public float Impostos_est { get; set; }
        public float Impostos_mun { get; set; }
        public int Idnfbaseada { get; set; }
        public float Oskminicial { get; set; }
        public float Oskmfinal { get; set; }
        public int Cancelada { get; set; }
        public string Md5 { get; set; }
        public int Crz { get; set; }
        public int Coo { get; set; }
        public int Ccf { get; set; }
        public int Finalidade { get; set; }
        public int Idmodelo { get; set; }
        public string Tipocarteira { get; set; }
        public float Piscofinssomado { get; set; }
        public int Idveiculo { get; set; }
        public int Emedicao { get; set; }
        public float Totalitens { get; set; }
        public DateTime Datafiscal { get; set; }
        public int Idrepresentante { get; set; }
        public float Valordescontos_prod { get; set; }
        public float Valordescontos_nf { get; set; }
        public float Impostostotais { get; set; }
        public float Valordinheiro { get; set; }
        public float Valorprazo { get; set; }
        public float Valorcdebito { get; set; }
        public float Valorccredito { get; set; }
        public float Valorccorrente { get; set; }
        public int Idequipamento { get; set; }
        public string Equipamentodescricao { get; set; }
        public int Idcomanda { get; set; }
        public float Aliquotaiss { get; set; }
        public float Baseiss { get; set; }
        public float Valoriss { get; set; }
        public DateTime Datamanifesto { get; set; }
        public int Statusmanifesto { get; set; }
        public string Eventomanifesto { get; set; }
        public string Xeventomanifesto { get; set; }
        public string Protocolomanifesto { get; set; }
        public int Bloq_clientebloqueado { get; set; }
        public int Bloq_parcelaabaixo { get; set; }
        public int Bloq_parcelaacima { get; set; }
        public int Bloq_descontocliente { get; set; }
        public int Bloq_descontototal { get; set; }
        public string Xmotivo { get; set; }
        public int Idnfweb { get; set; }
        public int Sincronizado { get; set; }
        public string Xml { get; set; }
    }
}
