using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TechClient
{
    class Pessoas
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Endereco { get; set; }
        public string Numerorua { get; set; }
        public string Bairro { get; set; }
        public int Cxpostal { get; set; }
        public string Complemento { get; set; }
        public int Cidade { get; set; }
        public string Fone01 { get; set; }
        public string Fone02 { get; set; }
        public string Fone03 { get; set; }
        public string Fone04 { get; set; }
        public string Contato { get; set; }
        public string Celular { get; set; }
        public string Pessoafisicajuridica { get; set; }
        public string Cpfcnpj { get; set; }
        public string Rgie { get; set; }
        public DateTime Datanascimento { get; set; }
        public string Email { get; set; }
        public string Homepage { get; set; }
        public string Nomepai { get; set; }
        public string Nomemae { get; set; }
        public string Estadocivil { get; set; }
        public string Sexo { get; set; }
        public string Referenciacomercial { get; set; }
        public string Conjuge { get; set; }
        public string Restricaomotivo { get; set; }
        public int Bloquearvenda { get; set; }
        public string Cep { get; set; }
        public string Inscricaomunicipal { get; set; }
        public string Msn { get; set; }
        public int Contribuinteicms { get; set; }
        public int Contribuinteipi { get; set; }
        public string Orgaoemissorrg { get; set; }
        public DateTime Dataemissaorrg { get; set; }
        public int Suframa { get; set; }
        public DateTime Datahora_atualizacao { get; set; }
        public DateTime Dataultcompra { get; set; }
        public bool Cliente { get; set; }
        public bool Funcionario { get; set; }
        public bool Fornecedor { get; set; }
        public string Cte_rntrc { get; set; }
        public int Tributacao { get; set; }
        public int Motorista { get; set; }
        public string Trab_cnpj { get; set; }
        public string Trab_ie { get; set; }
        public string Trab_razaosocial { get; set; }
        public string Trab_fantasia { get; set; }
        public string Trab_endereco { get; set; }
        public string Trab_numero { get; set; }
        public string Trab_bairro { get; set; }
        public string Trab_cidadeuf { get; set; }
        public int Classificacao { get; set; }
        public int Atacado { get; set; }
        public string Iesustituto { get; set; }
        public int Vendedor { get; set; }
        public float Comissao { get; set; }
        public float Comissaoavista { get; set; }
        public float Comissaoaprazo { get; set; }
        public int Operadoracartao { get; set; }
        public int Consumidorfinal { get; set; }
        public int Ativo { get; set; }
        public string Ididentifid { get; set; }
        public float Limitecredito { get; set; }
        public int Bloqueialimite { get; set; }
        public int Bloqueiadebito { get; set; }
        public int Msglimite { get; set; }
        public int Msgdebito { get; set; }
        public int Transportador { get; set; }
        public int Operacaopadrao { get; set; }
        public string Origemrg { get; set; }
        public int Opservico { get; set; }
        public int Consultor { get; set; }
        public int Entregapecas { get; set; }
        public DateTime Hora1 { get; set; }
        public DateTime Hora2 { get; set; }
        public DateTime Hora3 { get; set; }
        public DateTime Hora4 { get; set; }
        public int Totalhorasmensais { get; set; }
        public float Parcelamaxima { get; set; }
        public float Desc_avista { get; set; }
        public float Desc_aprazo { get; set; }
        public float Desc_adebito { get; set; }
        public float Desc_acredito { get; set; }
        public float Desc_acc { get; set; }
        public DateTime Hora5 { get; set; }
        public DateTime Hora6 { get; set; }
        public DateTime Hora7 { get; set; }
        public DateTime Hora8 { get; set; }
        public DateTime Hora9 { get; set; }
        public DateTime Hora10 { get; set; }
        public DateTime Hora11 { get; set; }
        public DateTime Hora12 { get; set; }
        public DateTime Hora13 { get; set; }
        public DateTime Hora14 { get; set; }
        public DateTime Hora15 { get; set; }
        public DateTime Hora16 { get; set; }
        public DateTime Hora17 { get; set; }
        public DateTime Hora18 { get; set; }
        public DateTime Hora19 { get; set; }
        public DateTime Hora20 { get; set; }
        public DateTime Hora21 { get; set; }
        public DateTime Hora22 { get; set; }
        public DateTime Hora23 { get; set; }
        public DateTime Hora24 { get; set; }
        public DateTime Hora25 { get; set; }
        public DateTime Hora26 { get; set; }
        public DateTime Hora27 { get; set; }
        public DateTime Hora28 { get; set; }
        public int Usabarras { get; set; }
        public int Regimetributario { get; set; }
        public int Imprimenota { get; set; }
        public int Bloqueiadebitosenha { get; set; }
        public int Bloqueialimitesenha { get; set; }
        public int Diasaposvencido { get; set; }
        public float Valorservico { get; set; }
        public int Idvendedor { get; set; }
        public int Representante { get; set; }
        public int Pagacomissao { get; set; }
        public int Comissaototalnavenda { get; set; }
        public DateTime Ultimacompra { get; set; }
        public float Valorultimacompra { get; set; }
        public int Documento { get; set; }
        public int Mostraimpostoibpt { get; set; }
        public float Salario { get; set; }
        public string Conj_localtrab { get; set; }
        public string Conj_profissao { get; set; }
        public float Conj_salario { get; set; }
        public string Conj_cpf { get; set; }
        public string Conj_rg { get; set; }
        public DateTime Conj_nascimento { get; set; }
        public string Profissao { get; set; }
        public string Tempotrabalho { get; set; }
        public string Conj_tempotrabalho { get; set; }
        public int Sincronizado { get; set; }
        public int Idpessoasweb { get; set; }
        public int Idlistapreco { get; set; }
        public string Apolice { get; set; }
        public string Es_tipotrabalhador { get; set; }
        public int Es_agentenocivo { get; set; }
        public float Es_salariobase { get; set; }
        public int Es_horastrabalhadas { get; set; }
        public string Es_pis { get; set; }
        public DateTime Es_datainicio { get; set; }
    }
}
