using System;

namespace Modelo
{

    public class Nf
    {
        //dados básicos
        public int Id { get; set; }
        public int Codigo { get; set; }
        public int Documento { get; set; }
        public int Idpessoas { get; set; }
        public DateTime Dataentrada { get; set; }
        public DateTime Dataemissao { get; set; }
        public DateTime Hora { get; set; }
        public string Tipo { get; set; }
        public int Emissor { get; set; }
        public string Chavenfe { get; set; }
        public string Modelo { get; set; }
        public int Operacao { get; set; }
        public decimal Valorconsumo { get; set; }
        public decimal Valorenergia { get; set; }
        public decimal Valorservico { get; set; }
        public decimal Valorproduto { get; set; }
        public decimal Valortotal { get; set; }
        public decimal Baseicms { get; set; }
        public decimal Baseicmsst { get; set; }
        public decimal Basepis { get; set; }
        public decimal Basecofins { get; set; }
        public decimal Baseipi { get; set; }
        public decimal Valoricms { get; set; }
        public decimal Valoricmsst { get; set; }
        public decimal Valorpis { get; set; }
        public decimal Valorcofins { get; set; }
        public decimal Valoripi { get; set; }
        public decimal Valorfrete_somado { get; set; }
        public decimal Valorfrete { get; set; }
        public decimal Valoroutros_somado { get; set; }
        public decimal Valoroutros { get; set; }
        public decimal Valordesconto { get; set; }
        public decimal Valoracrescimo { get; set; }
        public int Serie { get; set; }
        public int Ambiente { get; set; }
        public int Emissao { get; set; }
        public string Status { get; set; }
        public string Protocolo { get; set; }
        public string Recibo { get; set; }
        public string Horarecibo { get; set; }
        public string Observacao { get; set; }
        public string Observacaofisco { get; set; }
        public int Tipofrete { get; set; }
        public int Idtransportador { get; set; }
        public string Placa { get; set; }
        public string Ufveiculo { get; set; }
        public string Rntc { get; set; }
        public decimal Quantidadevolume { get; set; }
        public string Especievolume { get; set; }
        public string Marcavolume { get; set; }
        public string Numerovolume { get; set; }
        public decimal Pesolvolume { get; set; }
        public decimal Pesobvolume { get; set; }
        public DateTime Data_atualizacao { get; set; }
        public string Ufdesembarque { get; set; }
        public string Localdesembarque { get; set; }
        public int Funcionario { get; set; }
        public int Idapto { get; set; }
        public int Empresa { get; set; }
        public int Idviagem { get; set; }
        public int Idcaixa { get; set; }
        public int Idvendedor { get; set; }
        public string Nomepessoa { get; set; }
        public string Localentrega { get; set; }
        public decimal Comissao { get; set; }
        public string Requisitante { get; set; }
        public int Idplanovenda { get; set; }
        public int Idorigem { get; set; }
        public int Entrega { get; set; }
        public int Retirada { get; set; }
        public int Nfpropria { get; set; }
        public DateTime Horasaida { get; set; }
        public int Idecf { get; set; }
        public string Cnpjdigitado { get; set; }
        public decimal Percentualimp { get; set; }
        public string Comb_placa { get; set; }
        public int Comb_kmplaca { get; set; }
        public decimal Impostos_nac { get; set; }
        public decimal Impostos_imp { get; set; }
        public decimal Impostos_est { get; set; }
        public decimal Impostos_mun { get; set; }
        public int Idnfbaseada { get; set; }
        public decimal Oskminicial { get; set; }
        public decimal Oskmfinal { get; set; }
        public int Cancelada { get; set; }
        public string Md5 { get; set; }
        public int Crz { get; set; }
        public int Coo { get; set; }
        public int Ccf { get; set; }
        public int Finalidade { get; set; }
        public int Idmodelo { get; set; }
        public string Tipocarteira { get; set; }
        public decimal Piscofinssomado { get; set; }
        public int Idveiculo { get; set; }
        public int Emedicao { get; set; }
        public decimal Totalitens { get; set; }
        public DateTime Datafiscal { get; set; }
        public int Idrepresentante { get; set; }
        public decimal Valordescontos_prod { get; set; }
        public decimal Valordescontos_nf { get; set; }
        public decimal Impostostotais { get; set; }
        public decimal Valordinheiro { get; set; }
        public decimal Valorprazo { get; set; }
        public decimal Valorcdebito { get; set; }
        public decimal Valorccredito { get; set; }
        public decimal Valorccorrente { get; set; }
        public int Idequipamento { get; set; }
        public string Equipamentodescricao { get; set; }
        public int Idcomanda { get; set; }
        public decimal Aliquotaiss { get; set; }
        public decimal Baseiss { get; set; }
        public decimal Valoriss { get; set; }
        public DateTime Datamanifesto { get; set; }
        public int Statusmanifesto { get; set; }
        public string Eventomanifesto { get; set; }
        public string Xeventomanifesto { get; set; }
        public string Protocolomanifesto { get; set; }
        public int Bloq_clientebloqueado { get; set; }
        public int Bloq_parcelaabaixo { get; set; }
        public int Bloq_parcelaacima { get; set; }
        public int Bloq_descontocliente { get; set; }
        public int Bloq_descontototal { get; set; }
        public string Xmotivo { get; set; }
        public int Idweb { get; set; }
        public int Idfolk { get; set; }
        public string Xml { get; set; }
    }
}